config/routes.rb
Rails.application.routes.draw do

  get 'admin_sessions/new'

  get 'sessions/new'
  #get 'allchecklist', to:'static_pages#checklist'
  get 'borders/new'
  patch '/borders/:id/update', to:'borders#update' ,as:'update'
  get '/borders/:id/edit', to:'borders#edit', as:'edit'
  get '/borders/:id' , to:'borders#show', as:'profile'
  root 'static_pages#home'
  get 'signup' ,to:'borders#new'
  post 'signup' ,to:'borders#create'
  post 'ungroup',to:'borders#ungroup'

  get 'hello' ,to:'borders#hello'

  
  get '/checklist/:year', to: 'borders#checklist', as: 'checklist'
  resources :borders


  get 'login', to:'sessions#new'
  post 'login' , to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #for admin
  get 'adminlogin', to:'admin_sessions#new'
  post 'adminlogin', to:'admin_sessions#create'
  delete 'adminlogout', to:'admin_sessions#destroy'
  resources :admins
  get 'admins/:id', to:'admins#show',as:'adminprofile'
  get '/:hostelname/list',to:'admins#borderslist', as:'borderslist'
  get 'download',to:'admin#download'
  get 'preference',to:'admins#checkpreference'

  #generatelist
  post 'generate', to: 'preferences#create'
  
  get 'setdatetime', to:'admins#setdatetimepage'
  post 'setdatetime' , to:'preferences#setdatetime'

  #room allotment
  get 'newallotement',to:'room_allotements#start'
  get 'roomallotement',to:'room_allotements#show'
  get 'roomallotementhello',to:'room_allotements#hello'
  post 'roomallotement',to:'room_allotements#create'
  get 'allotement',to:'room_allotements#allotement'

  #settings
  get 'setting', to:'settings#show'
  post 'newhostel', to:'settings#newhostel'
  post 'import', to:'settings#import'

  post 'import_student_result', to:'settings#import_student_result'

  post 'create_profile', to:'settings#create_profile'

  post 'add' ,to: 'room_allotements#add'
  post 'remove' ,to: 'room_allotements#remove'
end

app/models/.rb
class  < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/abc.rb
class Abc < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/admin.rb
class Admin < ApplicationRecord
	validates :name, presence:true,length:{maximum:50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/models/border.rb
class Border < ApplicationRecord
  #before_save { self.email = email.downcase }
  validates :roll_no ,presence: true,length:{maximum:10},uniqueness:true
  validates :name,length:{maximum:50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, length: { maximum: 255 }
                    #format: { with: VALID_EMAIL_REGEX }
                    #uniqueness: { case_sensitive: false }


  VALID_PHONE_REGEX=/\A[0-9]+\z/i
  validates :phone_no,length:{maximum:10}
  #format:{with:VALID_PHONE_REGEX}
  
  has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  #associations
  belongs_to :hostel , polymorphic:true
  

  belongs_to :student_result

  #validate :border_count_within_limit, :on => :create, :on => :update

  #def border_count_within_limit
   # if self.hostel.borders(:reload).length >= self.hostel.no_of_rooms
    #  errors.add(:base, "Exceeded thing limit")
    #end
  #end

end

app/models/choice.rb
class Choice < ApplicationRecord
	has_many :roommates ,:dependent => :destroy

	has_many :room_choices,:dependent => :destroy
end

app/models/himadri.rb
class Himadri < ApplicationRecord
	has_many :borders, as: :hostel
	 
end

app/models/himgiri.rb
class Himgiri < ApplicationRecord
	has_many :borders, as: :hostel
end

app/models/hostel.rb
class Hostel < ApplicationRecord
	validates :hostel_name ,presence: true,uniqueness:true
end

app/models/kailash.rb
class Kailash < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/ki.rb
class Ki < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/kiru.rb
class Kiru < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/manish.rb
class Manish < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/neelkanth.rb
class Neelkanth < ApplicationRecord
	has_many :borders, as: :hostel
	
end

app/models/preftab1.rb
class Preftab1 < ApplicationRecord
end

app/models/preftab2.rb
class Preftab2 < ApplicationRecord
end

app/models/preftab3.rb
class Preftab3 < ApplicationRecord
end

app/models/preftab4.rb
class Preftab4 < ApplicationRecord
end

app/models/roommate.rb
class Roommate < ApplicationRecord
	belongs_to :choice
end

app/models/temphostel.rb
class Temphostel < ApplicationRecord
end

app/models/thi.rb
class Thi < ParentHostel
 has_many :borders, as: :hostel
 end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/checklist.html.erb
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>CHECKLIST</title>
    
</head>

<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #dddddd;
}

ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a, .dropbtn {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover, .dropdown:hover .dropbtn {
    background-color: white;
}

li.dropdown {
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
    text-align: left;
}

.dropdown-content a:hover {background-color: #f1f1f1}

.dropdown:hover .dropdown-content {
    display: block;
}    
</style>

<body >

<div>
   <ul>
  <li><%= link_to "Home",root_path %></li>
  
</ul> 
</div>

<div class="row text-center">
                 <div class="col-lg-8 col-lg-offset-2 col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
                     <h1 data-scroll-reveal="enter from the bottom after 0.1s" class="header-line" >CHECKLIST</h1>
                 </div>
            </div>

<% @borders.each do |border| %>
 <%if !border.nil?%>
<table>
  <tr>
    <th>ROLL No.</th>
    <th>CGPI</th>
    <th>START Time</th>
    <th>END TIME</th>
  </tr>
  
 
    <%border.each do |f| %>
    <tr>

    <td><%= f.roll_no %></td>
    <td><%= f.cgpi %></td>
    <td><%= f.start %></td>
    <td><%=f.endtime %></td>
  </tr>
  <% end %>
  
</table>
<%end%>
<%end%>




    

</body>
</html>

app/views/static_pages/home.html.erb
<!-- navigation bar starts-->
<nav class="navbar navbar-default navbar-static-top nav-set" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
		    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#indexnav">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
		<a class="navbar-brand" href="#">WELCOME TO HOSTEL ALLOTMENT</a>
		</div>
		<div class="collapse navbar-collapse navbar-right " id="indexnav">
			<ul class="nav navbar-nav nav-tabs">
  			         <li><a href="#">ABOUT</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">CHECKLIST<b class="caret"></b></a>
            <ul class="dropdown-menu ">
              <li><%= link_to "1st-year",checklist_path("1")%></li>
              <li><%= link_to "2nd-year",checklist_path("2")%></li>
              <li><%= link_to "3rd-year",checklist_path("3")%></li>
              <li><%= link_to "4th-year",checklist_path("4")%></li>
            </ul>
          </li>
          <% if current_user.nil? %>
				 <li><%= link_to "ADMIN",adminlogin_path%></li>
         <%else%>
         <li><%= link_to "PROFILE",profile_path(current_user.id)%></li>
         <%end%>
				</ul>
		</div>
	</div>
	
</nav>
<!-- navigation bar end-->
<!-- body section shuru-->
<div class="panel">
<div class="row set-body-margin jumbotron">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
      <div class="col-md-4 col-sm-4 col-xs-12"><!--class="text-justified","text-center,text-right " will used-->
        <div class="panel panel-default">
          <div class="panel-heading text-center ">
              <h2 class="panel-title">INSTRUCTIONS</h2>
            </div>
          <div class="panel-instbody text-justified">
            <p><!--add instruction here-->
            
                </p>
          </div>
        </div>
      </div>
      <div class="col-md-4  col-sm-4 col-xs-12"> <!--also use col-md-pull-* & col-md-push-* -->  
         <div class="panel panel-default">
		        <div class="panel-heading text-center ">
			         <h2 class="panel-title">STUDENT LOGIN FORM </h2>
		        </div>
            <div class="panel-body">
            <%= form_for(:session, url: login_path) do |f| %>
         	
           			 <div class="form-group">
              				<label for="rollno">Roll No</label>
                      
                      <%= f.text_field :roll_no, class: 'form-control',placeholder:"UserId" , id:'rollno'%>
                      
              				
            			</div>
            			<div class="form-group">
              				<label for="exampleInputPassword1">Password</label>
                      <%= f.password_field :password, class: 'form-control',id: 'exampleInputPassword1',placeholder:"Password"%>
            			</div>
            			<% if current_user.nil? %>
            			<button type="submit" class="btn btn-default">Submit</button>
		              
                  <% else %>
                    <button type="submit" class="btn btn-default" disabled>Submit</button>
                    <% end %>
                <% end%>
            </div>
          </div>
      </div>
      <div class="col-md-4  col-sm-4 col-xs-12">
           <div class="panel panel-default">
                      <div class="panel-heading text-center"><h3 class="panel-title">HOSTELS MAP</h3></div>
                        <div class="panel-body ">
                            <div class="list-group">
                              <a href="#" class="list-group-item ">Himgiri hostel
                              </a>
                              <a href="#" class="list-group-item">himadri  hostel
                              </a>
                              <a href="#" class="list-group-item">Neelkanth Hostel
                              </a>
                              <a href="#" class="list-group-item ">Daluadar hostel
                              </a>
                              <a href="#" class="list-group-item">Neelkanth hostel
                              </a>
                              <a href="#" class="list-group-item">Vidyachal hostel
                              </a>
                            </div>
                        </div>
                      </div>
          </div>
      </div>
</div>
</div>
<!-- body section end-->

app/views/static_pages/home1.html.erb
  <div class="center jumbotron">
  <h1>Welcome </h1>
  <h2>To The NITH Hostel Room Alotment Portal</h2>
  <h3> click here to <a href="#">proceed</h3>
</div>

app/views/static_pages/home2.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>NITH HOSTEL ALLOTMENT</title>
    <!-- BOOTSTRAP CORE STYLE CSS -->
</head>
<body >
   
 <div class="navbar navbar-inverse navbar-fixed-top " id="menu">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><img class="logo-custom" src="" alt=""  /></a>
            </div>
            <div class="navbar-collapse collapse move-me">
                <ul class="nav navbar-nav navbar-right">
                     <li><a href="#features-sec">LOGIN</a></li>
                     <li><%= link_to "ADMIN LOGIN",adminlogin_path%></li>
                     
                </ul>
            </div>
           
        </div>
    </div>
      <!--NAVBAR SECTION END-->
       <div class="home-sec" id="home" >
           <div class="overlay">
 <div class="container">
           <div class="row text-center " >
           
               <div class="col-lg-12  col-md-12 col-sm-12">
               
                <div class="flexslider set-flexi" id="main-section" >
                    <ul class="slides move-me">
                        <!-- Slider 01 -->
                        <li>
                              
                           <h1>NITH HOSTEL ALLOTMENT</h1>
                           
                            <a  href="#features-sec" class="btn btn-info btn-block btn-lg" >
                                LOGIN
                            </a>
                             
                        </li>
                        <!-- End Slider 01 -->
                        
                    </ul>
                </div>
                   
     
              
              
            </div>
                
               </div>
                </div>
           </div>
           
       </div>
       <!--HOME SECTION END-->   
    <div  class="tag-line" >
         <div class="container">
           <div class="row  text-center" >
           
               <div class="col-lg-12  col-md-12 col-sm-12">
               
        <h2 data-scroll-reveal="enter from the bottom after 0.1s" ><i class="fa fa-circle-o-notch"></i> WELCOME TO THE NITH HOSTEL ALLOTMENT <i class="fa fa-circle-o-notch"></i> </h2>
                   </div>
               </div>
             </div>
        
    </div>
    <!--HOME SECTION TAG LINE END-->   
         <div id="features-sec" class="container set-pad" >
             <div class="row text-center">
                 <div class="col-lg-8 col-lg-offset-2 col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
                     <h1 data-scroll-reveal="enter from the bottom after 0.2s"  class="header-line">ALLOTMENT CRITERIA INFORMATION</h1>
                     <p data-scroll-reveal="enter from the bottom after 0.3s" >
                      How the Students would be alloted the following room and the eligibility.
                         </p>
                 </div>

             </div>
             <!--/.HEADER LINE END-->


           
   
    <!-- FACULTY SECTION END-->
      
      <!-- COURSES SECTION END-->
    <div id="contact-sec"   >
           <div class="overlay">
 <div class="container set-pad">
      <div class="row text-center">
                 <div class="col-lg-8 col-lg-offset-2 col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
                     <h1 data-scroll-reveal="enter from the bottom after 0.1s" class="header-line" >LOGIN FORM</h1>
                     <p data-scroll-reveal="enter from the bottom after 0.3s">
                      Enter your credentials as provided by the admin.</br>
                      Enter your UserId and Password to Step Forward.
                         </p>
                 </div>

             </div>
             <!--/.HEADER LINE END-->
           <div class="row set-row-pad"  data-scroll-reveal="enter from the bottom after 0.5s" >
           
               
                 <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
                    <%= form_for(:session, url: login_path) do |f| %>
                        <div class="form-group">
                            <%= f.text_field :roll_no, class: 'form-control',placeholder:"UserId" %>
                        </div>
                        <div class="form-group">
                          <%= f.password_field :password, class: 'form-control',placeholder:"Password"%>
                        </div>
                        
                        <div class="form-group">
                            <button type="submit" class="btn btn-info btn-block btn-lg" onclick="window.location.href='form.html'">LOGIN</button>
                        </div>

                    <% end %>
                </div>

               </div>
                </div>
          </div> 
       </div>
   
    <!--  Jquery Core Script -->
    
</body>
</html>