config/routes.rb
Rails.application.routes.draw do

  get 'admin_sessions/new'

  get 'sessions/new'
  #get 'allchecklist', to:'static_pages#checklist'
  get 'borders/new'
  patch '/borders/:id/update', to:'borders#update' ,as:'update'
  get '/borders/:id/edit', to:'borders#edit', as:'edit'
  get '/borders/:id' , to:'borders#show', as:'profile'
  root 'static_pages#home'
  get 'signup' ,to:'borders#new'
  post 'signup' ,to:'borders#create'
  post 'ungroup',to:'borders#ungroup'

  get 'hello' ,to:'borders#hello'

  
  get '/checklist/:year', to: 'borders#checklist', as: 'checklist'
  resources :borders


  get 'login', to:'sessions#new'
  post 'login' , to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #for admin
  get 'adminlogin', to:'admin_sessions#new'
  post 'adminlogin', to:'admin_sessions#create'
  delete 'adminlogout', to:'admin_sessions#destroy'
  resources :admins
  get 'admins/:id', to:'admins#show',as:'adminprofile'
  get '/:hostelname/list',to:'admins#borderslist', as:'borderslist'
  get 'download',to:'admin#download'
  get 'preference',to:'admins#checkpreference'

  #generatelist
  post 'generate', to: 'preferences#create'
  
  get 'setdatetime', to:'admins#setdatetimepage'
  post 'setdatetime' , to:'preferences#setdatetime'

  #room allotment
  get 'newallotement',to:'room_allotements#start'
  get 'roomallotement',to:'room_allotements#show'
  get 'roomallotementhello',to:'room_allotements#hello'
  post 'roomallotement',to:'room_allotements#create'
  get 'allotement',to:'room_allotements#allotement'

  #settings
  get 'setting', to:'settings#show'
  post 'newhostel', to:'settings#newhostel'
  post 'import', to:'settings#import'

  post 'import_student_result', to:'settings#import_student_result'

  post 'create_profile', to:'settings#create_profile'

  post 'add' ,to: 'room_allotements#add'
  post 'remove' ,to: 'room_allotements#remove'
end

app/models/.rb
class  < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/abc.rb
class Abc < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/admin.rb
class Admin < ApplicationRecord
	validates :name, presence:true,length:{maximum:50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/models/border.rb
class Border < ApplicationRecord
  #before_save { self.email = email.downcase }
  validates :roll_no ,presence: true,length:{maximum:10},uniqueness:true
  validates :name,length:{maximum:50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, length: { maximum: 255 }
                    #format: { with: VALID_EMAIL_REGEX }
                    #uniqueness: { case_sensitive: false }


  VALID_PHONE_REGEX=/\A[0-9]+\z/i
  validates :phone_no,length:{maximum:10}
  #format:{with:VALID_PHONE_REGEX}
  
  has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  #associations
  belongs_to :hostel , polymorphic:true
  

  belongs_to :student_result

  #validate :border_count_within_limit, :on => :create, :on => :update

  #def border_count_within_limit
   # if self.hostel.borders(:reload).length >= self.hostel.no_of_rooms
    #  errors.add(:base, "Exceeded thing limit")
    #end
  #end

end

app/models/choice.rb
class Choice < ApplicationRecord
	has_many :roommates ,:dependent => :destroy

	has_many :room_choices,:dependent => :destroy
end

app/models/himadri.rb
class Himadri < ApplicationRecord
	has_many :borders, as: :hostel
	 
end

app/models/himgiri.rb
class Himgiri < ApplicationRecord
	has_many :borders, as: :hostel
end

app/models/hostel.rb
class Hostel < ApplicationRecord
	validates :hostel_name ,presence: true,uniqueness:true
end

app/models/kailash.rb
class Kailash < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/ki.rb
class Ki < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/kiru.rb
class Kiru < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/manish.rb
class Manish < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/neelkanth.rb
class Neelkanth < ApplicationRecord
	has_many :borders, as: :hostel
	
end

app/models/preftab1.rb
class Preftab1 < ApplicationRecord
end

app/models/preftab2.rb
class Preftab2 < ApplicationRecord
end

app/models/preftab3.rb
class Preftab3 < ApplicationRecord
end

app/models/preftab4.rb
class Preftab4 < ApplicationRecord
end

app/models/roommate.rb
class Roommate < ApplicationRecord
	belongs_to :choice
end

app/models/temphostel.rb
class Temphostel < ApplicationRecord
end

app/models/thi.rb
class Thi < ParentHostel
 has_many :borders, as: :hostel
 end

app/views/admins/borderslist.html.erb
<nav class="navbar navbar-default navbar-static-top nav-set" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#indexnav">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
        <a class="navbar-brand" href="#">ADMIN INTERFACE</a>
        </div>
        <div class="collapse navbar-collapse navbar-right " id="indexnav">
            <ul class="nav navbar-nav nav-tabs">
                 <li><%= link_to "PROFILE",adminprofile_path(current_admin.id) %></li>
                <li><%= link_to "LOGOUT",adminlogout_path ,method: "delete"%></li>
                </ul>
        </div>
    </div>
    
</nav>
<div class="panel">
<div class="row set-body-margin jumbotron set-margin">
<%= link_to 'Download as .xlsx', borderslist_path(format: :xlsx) ,class:"btn btn-primary btn-block" %>
  <h2 class="header text-center"><u>Boarder List</u></h1>
    <div class="container">
        <nav aria-label="Page navigation">
          <ul class="pager justify-content-center">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover table-condensed"><!--table stripped also be used-->
                          <thead>
                            <tr>
                              <th>Room NO</th>
                              <th>Name</th>
                              <th>Roll No</th>
                            </tr>
                          </thead>
                          <tbody>
                            <% @rooms.each do |room|%>
                            <%room.borders.each do |border| %>
                            <tr>
                                <td><%=room.room_no%></td>
                                <td><%=border.name%></td>
                                <td><%=border.roll_no%> </td>
                             <%end%>
                             </tr>
                             <%end%>

                          </tbody>
                        </table>
                    </div>

            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
          </ul>
        </nav>
    </div>
</div>
</div>
</div>

app/views/admins/checkpreference.html.erb
<div class="set-margin">
<div class="panel">
<div class="row set-body-margin jumbotron text-center">
    <h2 class="header"></h2>
    <div class="row">
          <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
        <ul>
        	<%@students.each do |student| %>
				<%=student.roll_no%>
				<%=student.cgpi%>
				<%=student.roomie1%>
				<%=student.roomie2%>
				<%=student.room1%>
				<%=student.room2%><br>
			<%end%>
        </ul>
        <li><%= link_to "allote",allotement_path%></li>
      </div>
      </div>
</div>
</div>
</div>
</div>

app/views/admins/new.html.erb
<% provide(:title, "Log in") %>
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:admin, url: login1_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admins/setdatetimepage.html.erb
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>FORM</title>
</head>

<style type="text/css">
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a, .dropbtn {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover, .dropdown:hover .dropbtn {
    background-color: white;
}

li.dropdown {
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
    text-align: left;
}

.dropdown-content a:hover {background-color: #f1f1f1}

.dropdown:hover .dropdown-content {
    display: block;
}    
</style>

<body >

<div>
   <ul>
  <li><%= link_to "Profile",profile_path(current_admin.id) %></li>
  <li><%= link_to "Check List",checklist_path %></li>
  <li><%= link_to "Logout",logout_path ,method: "delete"%></li>
</ul> 

</div>
          <%= form_for(:preference, url:setdatetime_path) do |f| %>

            <div class="row text-center">
                 <div class="col-lg-8 col-lg-offset-2 col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
                         <h1 data-scroll-reveal="enter from the bottom after 0.1s" class="header-line" >SET DATE AND TIME OF ALLOCATION</h1>
                 </div>
            </div>

                        <div class="form-group">
                        	<%= f.datetime_select :DateTime%>
                        </div></br>

                        <div class="form-group">
                            <button type="submit" class="btn btn-info btn-block btn-lg">SUBMIT</button>
                        </div>

            <% end %>
</body>
</html>

app/views/admins/show.html.erb
<script>
$(document).ready(function() {

    $("#hostel_type").change(function() {
        var val = $(this).val();
        <% @hostels.each do |hostel| %>
          if (val == "<%=raw hostel%>") {
           $(".multiselect").html("<%@floors[hostel].each do |floor|%><label><span class'input-group-adddon'><input type='checkbox' name='floors[]' value='<%=floor%>' class='floor_type' id=<%=floor%> /></span><input type='text' size='10' placeholder='<%=floor%>'-floor disabled/></label><%end%>");
        }
        <%end%>
        $(".multiselect1").html('');
    });
 
    $(document).on('click','.floor_type',function() {
        var val = $(this).attr('id');
        var val1=$('#'+val).val();
        var val2=$("#hostel_type").val();
        var ischecked= $('#'+val).is(':checked');
        if (ischecked){
         
        <% @hostels.each do |hostel| %>
        if (val2=="<%= raw hostel%>"){
          <%@floors[hostel].each do |floor|%>
          if(val1=="<%= raw floor%>"){
        $(".multiselect1").append("<div class='row'><div class='col-md-7 col-md-offset-4'><label class='<%=floor%>'><input type='text' size='15' placeholder='<%= floor%>'-floor-rooms disabled/></label></div></div><div class='row'><div class='col-md-10 col-md-offset-1 '><%@rooms[hostel][floor].each do |room|%><label class='<%=floor%>'><span class'input-group-adddon'><input type='checkbox' name='rooms[]' value=<%=room%> checked/></span><input type='text' size='5' placeholder=<%=room%> disabled/></label><%end%></div> </div>");
        
        }

        <%end%>
        }

        <%end%>
      }
      else
      {
          $("."+val1).remove();
      }
      
        
          
           
        
        
    });

    jQuery.fn.multiselect = function() {
    $(this).each(function() {
        var checkboxes = $(this).find("input:checkbox");
        checkboxes.each(function() {
            var checkbox = $(this);
            // Highlight pre-selected checkboxes
            if (checkbox.prop("checked"))
                checkbox.parent().addClass("multiselect-on");
 
            // Highlight checkboxes that the user selects
            checkbox.click(function() {
                if (checkbox.prop("checked"))
                    checkbox.parent().addClass("multiselect-on");
                else
                    checkbox.parent().removeClass("multiselect-on");
            });
        });
    });
};

$(function() {
     $(".multiselect").multiselect();
});
jQuery.fn.multiselect1 = function() {
    $(this).each(function() {
        var checkboxes = $(this).find("input:checkbox");
        checkboxes.each(function() {
            var checkbox = $(this);
            // Highlight pre-selected checkboxes
            if (checkbox.prop("checked"))
                checkbox.parent().addClass("multiselect-on");
 
            // Highlight checkboxes that the user selects
            checkbox.click(function() {
                if (checkbox.prop("checked"))
                    checkbox.parent().addClass("multiselect-on");
                else
                    checkbox.parent().removeClass("multiselect-on");
            });
        });
    });
};

$(function() {
     $(".multiselect1").multiselect();
});
  });
</script>




<style>
.multiselect label
{
  float:left;
}
.multiselect1 label
{
  float:left;
}
.background-colorp
{

  background: #808B96 ;
  
   border-style: solid;
   border-color: #17202A;
   border-width: 2px;
   
}
.hfloor
{
  height:100px;
}
.hroom
{
   height:300px;
  overflow-x: hidden; /* Hide horizontal scrollbar */
    overflow-y: scroll;
}

</style>
<!-- .multiselect {
    width:20em;
    height:15em;
    border:solid 1px #c0c0c0;
    overflow:auto;
}
 
.multiselect label {
    display:block;
}
 
.multiselect-on {
    color:#ffffff;
    background-color:#000099;
}
.multiselect1 {
    width:20em;
    height:15em;
    border:solid 1px #c0c0c0;
    overflow:auto;
}
 

.multiselect1-on {
    color:#ffffff;
    background-color:#000099;
}
</style>-->
 <!--navigation bar starts-->
  <nav class="navbar navbar-default navbar-static-top nav-set" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#indexnav">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
    <a class="navbar-brand" href="#">ADMIN INTERFACE</a>
    </div>
    <div class="collapse navbar-collapse navbar-right " id="indexnav">
      <ul class="nav navbar-nav nav-tabs">
        <li><li><%= link_to "PROFILE",adminprofile_path(current_admin.id)%></li>
        <li><%= link_to "ADD HOSTEL",setting_path%></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">CHECKLIST<b class="caret"></b></a>
            <ul class="dropdown-menu ">
              <li><%= link_to "1st-year",checklist_path("1")%></li>
              <li><%= link_to "2nd-year",checklist_path("2")%></li>
              <li><%= link_to "3rd-year",checklist_path("3")%></li>
              <li><%= link_to "4th-year",checklist_path("4")%></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">SELECT HOSTEL<b class="caret"></b></a>
            <ul class="dropdown-menu ">
              <% @hostels.each do |hostel|%>
                <li><%= link_to hostel,borderslist_path(hostel)%></li>
                <% end %>
            </ul>
          </li>
          <li><%= link_to "LOGOUT",adminlogout_path ,method: "delete"%></li>                       
        </ul>
    </div>
  </div>
  </div>
</nav> 
<div class="set-margin">
<div class="panel">
<div class="row set-body-margin jumbotron">
  <%= render 'shared/flash'%>
<!--class="text-justified","text-center,text-right " will used-->
        <div class="col-md-7 col-md-offset-1 col-sm-5 col-sm-offset-1 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading text-center ">
                  <h2 class="panel-title">SET NEW ALLOTMENT</h2>
                </div>
              <div class="panel-body text-center">
                <%= form_for(:preference, url: generate_path, class: 'form-inline') do |f| %>
                  <div class="row">
                    <div class="col-md-4 col-md-offset-1 col-sm-4 col-sm-offset-1 col-xs-12">
                      <div class="form-group">
                         <label for="select-year">SELECT YEAR</label>

                             <select list="year" name="year" class="form-control " required="required"  placeholder="select-year" />
                              <option disabled selected value>-select-year-</option>
                              <option value="1">1st-year
                              <option value="2">2nd-year
                              <option value="3">3rd-year
                              <option value="4">4th-year
                            </select>
                      </div>
                    </div>
                    <div class="col-md-4 col-md-offset-2 col-sm-4 col-sm-offset-2 col-xs-12">
                      <div class="form-group">
                        <label for="rollno">SELECT HOSTEL</label>
                          <select list="hostel-name" name="hostel2" class="form-control " required="required"  placeholder="select-hostel" id="hostel_type" />
                          <option disabled selected value >-select-hostel-</option>
                            <% @hostels.each do |hostel| %>
                              <option value=<%=hostel%>><%=hostel%>
                            <%end%>
                            </select>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-10  col-sm-4 col-sm-offset-1 col-xs-12">

                      <div class="form-group">
                        <label for="rollno">SELECT FLOOR</label>
                        <div class="panel panel-body background-colorp hfloor">
                            
                              <div class="input-group">
                              <div class="multiselect black-color">
                              </div>
                            
                            </div>
                    
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-10  col-sm-4 col-sm-offset-1 col-xs-12">

                      <div class="form-group">
                        <label for="rollno">SELECT ROOMS</label>
                        <div class="panel panel-body background-colorp hroom">
                            
                              
                              <div class="multiselect1 black-color">
                              </div>
                            
                            
                    
                        </div>
                      </div>
                    </div>
                  </div>
                
                  <div class="form-group ">
                        <label for="starttime">START TIME</label>
                        <div class="black-color">
                            <%= f.datetime_select :StartTime,class:"form-control "%>
                        </div>
                  </div>
                  <div class="form-group">
                        <label for="endtime">END TIME</label>
                        <div class="black-color">
                          <%= f.datetime_select :EndTime,class:"form-control"%></div>
                  </div>
                  <div class="form-group">
                            <button type="submit" class="btn btn-default btn-block">SUBMIT</button>
                  </div>
                <%end%>
              </div>
            </div>
        </div>
        <div class="col-md-2 col-md-offset-1  col-sm-3 col-sm-offset-2 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center ">
              <h2 class="panel-title">IMPORTANT LINKS</h2>

            </div>
            <div class="panel-body text-center">
            <!-- enter your link here-->
            <%= link_to "Allot Rooms",allotement_path,data: { confirm: 'Are you sure?' }%>
            </div>
            <div class="panel-body text-center">
            <%= link_to "Start New Allotment",newallotement_path,data: { confirm: 'This will start new allotement. Are you sure to continue?' }%>
          </div>
          </div>
        </div>
    </div>
</div>
</div>

app/views/admins/show1.html.erb
<%= @user.name %>
<%= link_to "logout",adminlogout_path ,method: "delete"%>
<%= link_to "Himgiri",borderslist_path("Himgiri")%>
<%= link_to "Himadri",borderslist_path("Himadri") %>
<%= link_to "Neelkanth",borderslist_path("Neelkanth")%>

<%= link_to "Set New Room Allotement",newallotement_path%>
<%= link_to "Start New Room Allotement",setdatetime_path%>

<div class="container">
  <h1> generate preference list</h1>
  <%= form_for(:preference, url: generate_path) do |f| %>
  <div>
    <h2>Select year</h2>
    <input type="checkbox" name="year" value="1"> 1st year<br>
    <input type="checkbox" name="year" value="2"> 2nd year<br>
    <input type="checkbox" name="year" value="3"> 3rd year<br>
  </div>
  <div>
    <h2>Select hostel1</h2>
    <input type="checkbox" name="hostel1[]" value="Himgiri"> Himgiri<br>
    <input type="checkbox" name="hostel1[]" value="Himadri"> Himadri<br>
    <input type="checkbox" name="hostel1[]" value="Neelkanth"> Neelkanth<br>
  </div>
  <div>
    <h2>select hostel2</h2>
    <input type="checkbox" name="hostel2[]" value="Himgiri"> Himgiri<br>
    <input type="checkbox" name="hostel2[]" value="Himadri"> Himadri<br>
    <input type="checkbox" name="hostel2[]" value="Neelkanth"> Neelkanth<br>
  </div>
  <input type="submit" value="Submit">
    
    <% end %>

</div>

 

app/views/admins/show2.html.erb
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>ADMIN</title>
   
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css' />
</head>
<style type="text/css" rel="stylesheet">
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #447;
}

li {
    float: left;
}

li a, .dropbtn {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover, .dropdown:hover .dropbtn {
    background-color: white;
}

li.dropdown {
    display: inline-block;
}

.dropdown-content {
    color:#777;
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
    text-align: left;
}

.dropdown-content a:hover {background-color: #f1f1f1}

.dropdown:hover .dropdown-content {
    display: block;
}
</style>
<body >
<li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hostels<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% @hostels.each do |hostel|%>
                <li><%= link_to hostel,borderslist_path(hostel)%></li>
                <% end %>
            </ul>
</li>
<ul>
<li><li><%= link_to "Home",root_path%></li>
<li><%= link_to "Set New Room Allotement",newallotement_path%></li>
<li><%= link_to "Start New Room Allotement",setdatetime_path%></li>
<li><%= link_to "check preferences",preference_path%></li>
<li><%= link_to "setting",setting_path%></li>
<li><%= link_to "logout",adminlogout_path ,method: "delete"%></li>
</ul>


            <%= form_for(:preference, url: generate_path) do |f| %>
            <div class="row text-center">
                 <div class="col-lg-8 col-lg-offset-2 col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
                     <h1 data-scroll-reveal="enter from the bottom after 0.1s" class="header-line" >SELECT YEAR</h1>
                 </div>
            </div>

            <div class="row set-row-pad"  data-scroll-reveal="enter from the bottom after 0.5s" >
            <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
                    
                    <section required="required">
                    
                        <div class="form-group">
                            <h4 align="center">1st Year</h4><input type="radio" class="form-control " name="year" value ="1">
                        </div>
                        <div class="form-group">
                            <h4 align="center">2nd Year</h4><input type="radio" class="form-control " name="year" value ="2">
                        </div>
                        <div class="form-group">
                            <h4 align="center">3rd Year</h4><input type="radio" class="form-control " name="year" value ="3">
                        </div></section>
                        
            
            <div class="row text-center">
                 <div class="col-lg-8 col-lg-offset-2 col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
                         <h1 data-scroll-reveal="enter from the bottom after 0.1s" class="header-line" >NEXT HOSTEL</h1>
                 </div>
            </div>

                        <% @hostels.each do |hostel| %>
                        <div class="form-group">
                            <h4 align="center"><%=hostel%></h4><input type="Checkbox" class="form-control " name="hostel2[]" value =<%=hostel%>>
                         </div>
                         <% end %>
                         <div class="form-group">
                           <%= f.select :category, options_for_select(@hostels), { :prompt => "Please select"}, {:multiple => true, :size =>10}  %>

                         </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-info btn-block btn-lg">SUBMIT</button>
                        </div>
                        
                        
                        
                       
                        
                    <% end %>
            </div>
            </div>

</body>
</html>

app/views/layouts/_footer.html.erb
<!-- footer section start-->
<div id="contact" class="set-margin footer-bottom-margin">
<footer class="site-footer"><!-- address tag will used, strong tag will used , abbr tag will used-->
        <div class="row bottom-footer">
          <div class="col-md-4 col-md-offset-1">Last Update: July,2017</div>
          <div class="col-md-3 ">National institute of technology Hamirpur(HP)
              </br>Copyright @ 2017 NIT Hamirpur</br>Fax:+91514546515
           </div>
          <div class="col-md-3 col-md-offset-1 ">
            <h4>Contact<span class="glyphicon glyphicon-envelope"></span>hostel.nith@gmail.com</h4>
         </div>
</div>
  </footer>
</div>

app/views/layouts/_header.html.erb
<!-- header section start-->
<!--repeated code for all pages-->
<div class="set-margin header-top-margin">
<div class="jumbotron no-margin no-padding ">
      <div class="container"><!--container centered the image-->
    <div class="row">
          <div class="col-md-3 col-md-offset-1 col-sm-6 col-xs-6">
            <%= image_tag("images.png", :alt => "rss feed", class: "img-responsive pull-left logo-height-width img-circle") %>
              
          </div>
          <div class="col-md-8 col-sm-6 col-xs-12">
                  <div class="row">
                      <div class="col-md-12 col-sm-12 col-xs-12">
                          <h2>NATIONAL INSTITUTE OF TECHNOLOGY HAMIRPUR</h2>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-8 col-md-offset-3 col-sm-12 col-xs-12">
                      <h2>HOSTEL ALLOTMENT</h2>
                  </div>
          </div>
    </div>
  </div>
</div>
</div>
<!-- header section end-->
<!-- navigation bar starts-->

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->