config/routes.rb
Rails.application.routes.draw do

  get 'admin_sessions/new'

  get 'sessions/new'
  #get 'allchecklist', to:'static_pages#checklist'
  get 'borders/new'
  patch '/borders/:id/update', to:'borders#update' ,as:'update'
  get '/borders/:id/edit', to:'borders#edit', as:'edit'
  get '/borders/:id' , to:'borders#show', as:'profile'
  root 'static_pages#home'
  get 'signup' ,to:'borders#new'
  post 'signup' ,to:'borders#create'
  post 'ungroup',to:'borders#ungroup'

  get 'hello' ,to:'borders#hello'

  
  get '/checklist/:year', to: 'borders#checklist', as: 'checklist'
  resources :borders


  get 'login', to:'sessions#new'
  post 'login' , to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #for admin
  get 'adminlogin', to:'admin_sessions#new'
  post 'adminlogin', to:'admin_sessions#create'
  delete 'adminlogout', to:'admin_sessions#destroy'
  resources :admins
  get 'admins/:id', to:'admins#show',as:'adminprofile'
  get '/:hostelname/list',to:'admins#borderslist', as:'borderslist'
  get 'download',to:'admin#download'
  get 'preference',to:'admins#checkpreference'

  #generatelist
  post 'generate', to: 'preferences#create'
  
  get 'setdatetime', to:'admins#setdatetimepage'
  post 'setdatetime' , to:'preferences#setdatetime'

  #room allotment
  get 'newallotement',to:'room_allotements#start'
  get 'roomallotement',to:'room_allotements#show'
  get 'roomallotementhello',to:'room_allotements#hello'
  post 'roomallotement',to:'room_allotements#create'
  get 'allotement',to:'room_allotements#allotement'

  #settings
  get 'setting', to:'settings#show'
  post 'newhostel', to:'settings#newhostel'
  post 'import', to:'settings#import'

  post 'import_student_result', to:'settings#import_student_result'

  post 'create_profile', to:'settings#create_profile'

  post 'add' ,to: 'room_allotements#add'
  post 'remove' ,to: 'room_allotements#remove'
end

app/models/.rb
class  < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/abc.rb
class Abc < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/admin.rb
class Admin < ApplicationRecord
	validates :name, presence:true,length:{maximum:50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/models/border.rb
class Border < ApplicationRecord
  #before_save { self.email = email.downcase }
  validates :roll_no ,presence: true,length:{maximum:10},uniqueness:true
  validates :name,length:{maximum:50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, length: { maximum: 255 }
                    #format: { with: VALID_EMAIL_REGEX }
                    #uniqueness: { case_sensitive: false }


  VALID_PHONE_REGEX=/\A[0-9]+\z/i
  validates :phone_no,length:{maximum:10}
  #format:{with:VALID_PHONE_REGEX}
  
  has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  #associations
  belongs_to :hostel , polymorphic:true
  

  belongs_to :student_result

  #validate :border_count_within_limit, :on => :create, :on => :update

  #def border_count_within_limit
   # if self.hostel.borders(:reload).length >= self.hostel.no_of_rooms
    #  errors.add(:base, "Exceeded thing limit")
    #end
  #end

end

app/models/choice.rb
class Choice < ApplicationRecord
	has_many :roommates ,:dependent => :destroy

	has_many :room_choices,:dependent => :destroy
end

app/models/himadri.rb
class Himadri < ApplicationRecord
	has_many :borders, as: :hostel
	 
end

app/models/himgiri.rb
class Himgiri < ApplicationRecord
	has_many :borders, as: :hostel
end

app/models/hostel.rb
class Hostel < ApplicationRecord
	validates :hostel_name ,presence: true,uniqueness:true
end

app/models/kailash.rb
class Kailash < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/ki.rb
class Ki < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/kiru.rb
class Kiru < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/manish.rb
class Manish < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/neelkanth.rb
class Neelkanth < ApplicationRecord
	has_many :borders, as: :hostel
	
end

app/models/preference1.rb
class Preference1 < ApplicationRecord
end

app/models/preftab1.rb
class Preftab1 < ApplicationRecord
end

app/models/preftab2.rb
class Preftab2 < ApplicationRecord
end

app/models/preftab3.rb
class Preftab3 < ApplicationRecord
end

app/models/preftab4.rb
class Preftab4 < ApplicationRecord
end

app/models/roommate.rb
class Roommate < ApplicationRecord
	belongs_to :choice
end

app/models/temphostel.rb
class Temphostel < ApplicationRecord
end

app/models/thi.rb
class Thi < ParentHostel
 has_many :borders, as: :hostel
 end

app/controllers/borders_controller.rb
class BordersController < ApplicationController
  before_action :logged_in_user, only:  [:index,:edit, :update,:show]
  before_action :correct_user, only: [:edit,:update]
  before_action :is_active, only: [:show]
  #before_action :is_allocation_start, only: [:checklist]

  def hello
    @border=Border.all
  end
  def new
    @user=Border.new
  end
  
  def show
    @user=Border.find(params[:id])
    @hostel=session[:hostel]
    if !@hostel.nil?
      @active="a"
      #@active=is_active?(@user)
    end

  end

  def edit
    @border=Border.find(current_user.id)
  end
  def update
    @border=Border.find(params[:id])
    @border.update(active:true)
    if @border.update_attributes(user_params)
      # Handle a successful update.
      redirect_to profile_path(@border.id)
    else
      @border.update(active:true)
    render 'edit'
  end
  end
  
  def create
    @user=Border.new(user_params)
    if @user.save
      log_in @user
      flash[:success]="Welcome to the NITH Hostel Room Alotments"
      redirect_to @user
      #jk
    else
      render 'new'
    end
  end

  def checklist1
    preferences=["Preference1","Preference2","Preference3"]
    roll_no=Border.find_by(id:session[:user_id]).roll_no
    preferences.each do |preference|
      preference_model=preference.constantize
      if !preference_model.find_by(roll_no:roll_no).nil?
        @borders=preference_model.all.order('cgpi DESC')
      end
    end
  end

  def checklist
    preferences={"1"=>"Preference1","2"=>"Preference2","3"=>"Preference3","4"=>"Preference4"}
    year=params[:year]
    preference=preferences[year]
    preference_model=preference.constantize
    @rank=0
    @borders=preference_model.all.order('cgpi DESC')
  end
  def ungroup
    current_user.grouped=false
    current_user.save
    a=Roommate.find_by(roommate:current_user.roll_no)
    if !a.nil?
      a.destroy
    end
    redirect_to current_user
  end
  
  private

    def user_params
      params.require(:border).permit(:roll_no,:name,:email,:phone_no,:parent_phone_no,:address)
    end

    def logged_in_user
      unless logged_in?
        store_location
        log_out
        flash[:danger] = "Please log in."
        redirect_to root_url
      end
    end
    # Confirms the correct user.
    def correct_user
      @user = Border.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

    def is_allocation_start
      redirect_to(root_url) unless !session[:hostel].nil?
    end

    def is_active
      redirect_to(edit_path(current_user.id)) unless current_user.active
    end

    def is_grouped
      redirect_to(current_user) unless current_user.grouped
    end

end

app/helpers/borders_helper.rb
module BordersHelper
	def is_active?(user)
		preferences=['Preference1','Preference2','Preference3',]
		preferences.each do |preference|
			preference_model=preference.constantize
			if !(temp_user=preference_model.find_by(roll_no:user.roll_no)).nil?
				if !temp_user.start.nil?
					if (temp_user.start<=DateTime.now && temp_user.endtime>=DateTime.now)
						return true
					else
						return false
					end
				else
					return false
				end
			end
		end

    end
end

app/views/borders/checklist.html.erb
<nav class="navbar navbar-default navbar-static-top nav-set" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#indexnav">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
    <a class="navbar-brand" href="#">WELCOME TO HOSTEL ALLOTMENT</a>
    </div>
    <div class="collapse navbar-collapse navbar-right " id="indexnav">
      <ul class="nav navbar-nav nav-tabs">
        <% if logged_in? %>
         <li><%= link_to "Profile",profile_path(current_user.id) %></li>
         <li><%= link_to "Logout",logout_path ,method: "delete"%></li>
         <% elsif admin_logged_in? %>
         <li><%= link_to "PROFILE",adminprofile_path(current_admin.id)%></li>
         <% else%>
         <% end %>
          
        </ul>
    </div>
  </div>
</nav>
<div class="panel">
<div class="row set-body-margin jumbotron set-margin">
  <h2 class="header text-center"><u>CHECKLIST</u></h1>
    <div class="container">
        <nav aria-label="Page navigation">
          <ul class="pager justify-content-center">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover table-condensed"><!--table stripped also be used-->
                          <tr>
                          <th>RANK</th>
                          <th>ROLL No.</th>
                          <th>CGPI</th>
                          </tr>
                           <% @borders.each do |border| %>
                          <tr>
                            <td><%=@rank+=1%></td>
                          <td><%= border.roll_no %></td>
                           <td><%= border.cgpi %></td>
                           </tr>
                          <% end %>
                        </table>
                    </div>
          </ul>
        </nav>
    </div>
</div>
</div>
</div>

app/views/borders/checklist1.html.erb
<% @borders.each do |border| %>
	<%= border.roll_no %>
	<%= border.cgpi %>
	<%= border.start %>
	<br>
	<%=border.endtime %>
<% end %>

app/views/borders/checklist2.html.erb
<nav class="navbar navbar-default navbar-static-top nav-set" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#indexnav">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
    <a class="navbar-brand" href="#">WELCOME TO HOSTEL ALLOTMENT</a>
    </div>
    <div class="collapse navbar-collapse navbar-right " id="indexnav">
      <ul class="nav navbar-nav nav-tabs">
         <li><%= link_to "Profile",root_url %></li>
          <li><%= link_to "Logout",'#' ,method: "delete"%></li>
        </ul>
    </div>
  </div>
</nav>
<div class="panel">
<div class="row set-body-margin jumbotron set-margin">
  <h2 class="header text-center"><u>CHECKLIST</u></h1>
    <div class="container">
        <nav aria-label="Page navigation">
          <ul class="pager justify-content-center">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover table-condensed"><!--table stripped also be used-->
                          <tr>
                          <th>ROLL No.</th>
                          <th>CGPI</th>
                          <th>START Time</th>
                          <th>END TIME</th>
                          </tr>
                           <% @borders.each do |border| %>
                          <tr>
                          <td><%= border.roll_no %></td>
                           <td><%= border.cgpi %></td>
                           <td><%= border.start %></td>
                          <td><%=border.endtime %></td>
                           </tr>
                          <% end %>
                        </table>
                    </div>
          </ul>
        </nav>
    </div>
</div>
</div>
</div>

app/views/borders/edit.html.erb
<!-- navigation bar starts-->
<!--reapeated code for select roommates.html & studentlogin.html-->
<nav class="navbar navbar-default navbar-static-top nav-set" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
		    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#profilenav">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
		<a class="navbar-brand" href="#">STUDENT INFORMATION</a>
		</div>
		<div class="collapse navbar-collapse navbar-right" id="profilenav">
			<ul class="nav navbar-nav nav-tabs">
				                  
			    	 <li><%= link_to "Profile",profile_path(current_user.id) %></li>
         <li><%= link_to "LOGOUT",logout_path ,method: "delete"%></li>

				</ul>
		</div>
	</div>
	
</nav>
<!-- navigation bar end-->
<!-- form start-->
<div class="panel">
<div class="jumbotron">
<div class="container">
  <div class="row">
<div class="col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12">
 <div class="panel panel-default">
		<div class="panel-heading text-center ">
			<h2 class="panel-title">ADD REST CREDENTIAL DETAILS </h2>
		</div>
          <div class="panel-body">
         	<%= form_for(@border, url: update_path(@border.id)) do |f| %>
				<div class="form-group">
           <%= f.label :rollno %>
          <%= f.text_field :roll_no, class: 'form-control',placeholder:@border.roll_no,disabled: true %>
    			
  					
			</div>
				
        <div class="form-group">
           <%= f.label :Name %>
          <%= f.text_field :name, class: 'form-control',placeholder:"Name",id:"studentname",required: true%>
    				
  					
			</div>
			<div class="form-group">
          <%= f.label :Email %>
          <%= f.email_field :email, class: 'form-control',placeholder:"enter your email",id:"studentemail",required: true %>
				
  			</div>
  			<div class="form-group">
            <%= f.label :"Student Phone no" %>
          <%= f.number_field :phone_no, class: 'form-control',placeholder:"student phone no",id:"studentphoneno",required: true %>
				</div>
			 <div class="form-group">
            <%= f.label :Parent %>
             <%= f.number_field :parent_phone_no, class: 'form-control',placeholder:"parent phone no",id:"parentphoneno",required: true %>
        </div>
         <div class="form-group">
            <%= f.label :Address %>
             <%= f.text_field :address, class: 'form-control',placeholder:"Address",id:"address",required: true %>
        </div>
  			<button type="submit" class="btn btn-default">Submit</button>
		<%end%>
  </div>
      </div>
    </div>
  </div>
   
</div>
</div>
</div>
</div>
<!--form end-->
<!--form body start-->

<!-form body end-->
<!-- form footer start-->

app/views/borders/hello.html.erb
<script>
$(document).ready(function() {
$("#table tr").click(function(){
   $(this).addClass('selected').siblings().removeClass('selected');    
   var value=$(this).find('td:first').html();   
});

$('.ok').on('click', function(e){
   
    alert($("#table tr.selected td:first").html());
});

});
</script>
<style>
td {border: 1px #DDD solid; padding: 5px; cursor: pointer;}

.selected {
    background-color: brown;
    color: #FFF;
}
</style>


<table id="table">
        <tr value='1'>
            <td>1 Ferrari F138</td>
            <td>1 000€</td>
            <td>1 200€</td>

        </tr>
        <tr>
            <td>2 Ferrari F138</td>
            <td>1 000€</td>
            <td>1 200€</td>

        </tr>
        <tr>
            <td>3 Ferrari F138</td>
            <td>1 000€</td>
            <td>1 200€</td>

        </tr>
    </table>
    <input type="button" name="OK" class="ok" value="OK"/>

app/views/borders/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user,url:signup_path) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :roll_no %>
      <%= f.text_field :roll_no %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>
      
      <%= f.label :address %>
      <%= f.text_field :address %>
      
      <%= f.label :phone_no %>
      <%= f.text_field :phone_no %>
      
      <%= f.label :room_no %>
      <%= f.text_field :room_no %>
      
      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/borders/show.html.erb
<nav class="navbar navbar-default navbar-static-top nav-set" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#indexnav">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
        <a class="navbar-brand" href="#">STUDENT HOMEPAGE</a>
        </div>
        <div class="collapse navbar-collapse navbar-right " id="indexnav">
            <ul class="nav navbar-nav nav-tabs">
                 <li><%= link_to "PROFILE",profile_path(current_user.id) %></li>
                <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">CHECKLIST<b class="caret"></b></a>
            <ul class="dropdown-menu ">
              <li><%= link_to "1st-year",checklist_path("1")%></li>
              <li><%= link_to "2nd-year",checklist_path("2")%></li>
              <li><%= link_to "3rd-year",checklist_path("3")%></li>
              <li><%= link_to "4th-year",checklist_path("4")%></li>
            </ul>
          </li>
                <li><%= link_to "UPDATE PROFILE",edit_path(current_user.id)%></li>
                <li><%= link_to "LOGOUT",logout_path ,method: "delete"%></li>
                </ul>
        </div>
    </div>
    
</nav>
<div class="panel">
<div class="row set-body-margin jumbotron text-center">
    <h2 class="header">WELCOME <%= @user.name%> </h2><hr>
    <div class="row">
          <div class="col-md-8 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <dl class= "dl-horizontal">
          <dt><h4>ROLLNO</h4></dt>
          <dd><h4><%= @user.roll_no%></h4></dd>
          <dt><h4>NAME</h4></dt>
          <dd><h4><%= @user.name %></h4></dd>
          <hr>
        </dl>
      </div>
      <%if  !@hostel.nil? %>
         
            <%if current_user.alloted? %>
                  <button class="btn btn-info disabled">ROOM ALREADY ALLOTTED</button>
            <% else %>
                <% if @active %>
                    <% if current_user.grouped%>
                       <%= link_to "you are grouped click to ungroup",ungroup_path,class: "btn btn-primary", method: "post"%>
                      <%else%>
                      <%= link_to "proceed for room allotment",roomallotement_path,class: "btn btn-primary" %>
                    <%end%>
                <%end%>
            <% end %>
            
        <% else %>
            <button class="btn btn-info disabled">ALLOTMENT IS NOT STARTED</button>
        <% end %>
      </div>
</div>
</div>
</div>

app/views/borders/update.html.erb
<%= @border.errors.messages%>