config/routes.rb
Rails.application.routes.draw do

  get 'admin_sessions/new'

  get 'sessions/new'
  #get 'allchecklist', to:'static_pages#checklist'
  get 'borders/new'
  patch '/borders/:id/update', to:'borders#update' ,as:'update'
  get '/borders/:id/edit', to:'borders#edit', as:'edit'
  get '/borders/:id' , to:'borders#show', as:'profile'
  root 'static_pages#home'
  get 'signup' ,to:'borders#new'
  post 'signup' ,to:'borders#create'
  post 'ungroup',to:'borders#ungroup'

  get 'hello' ,to:'borders#hello'

  
  get '/checklist/:year', to: 'borders#checklist', as: 'checklist'
  resources :borders


  get 'login', to:'sessions#new'
  post 'login' , to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #for admin
  get 'adminlogin', to:'admin_sessions#new'
  post 'adminlogin', to:'admin_sessions#create'
  delete 'adminlogout', to:'admin_sessions#destroy'
  resources :admins
  get 'admins/:id', to:'admins#show',as:'adminprofile'
  get '/:hostelname/list',to:'admins#borderslist', as:'borderslist'
  get 'download',to:'admin#download'
  get 'preference',to:'admins#checkpreference'

  #generatelist
  post 'generate', to: 'preferences#create'
  
  get 'setdatetime', to:'admins#setdatetimepage'
  post 'setdatetime' , to:'preferences#setdatetime'

  #room allotment
  get 'newallotement',to:'room_allotements#start'
  get 'roomallotement',to:'room_allotements#show'
  get 'roomallotementhello',to:'room_allotements#hello'
  post 'roomallotement',to:'room_allotements#create'
  get 'allotement',to:'room_allotements#allotement'

  #settings
  get 'setting', to:'settings#show'
  post 'newhostel', to:'settings#newhostel'
  post 'import', to:'settings#import'

  post 'import_student_result', to:'settings#import_student_result'

  post 'create_profile', to:'settings#create_profile'

  post 'add' ,to: 'room_allotements#add'
  post 'remove' ,to: 'room_allotements#remove'
end

app/models/.rb
class  < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/abc.rb
class Abc < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/admin.rb
class Admin < ApplicationRecord
	validates :name, presence:true,length:{maximum:50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/models/border.rb
class Border < ApplicationRecord
  #before_save { self.email = email.downcase }
  validates :roll_no ,presence: true,length:{maximum:10},uniqueness:true
  validates :name,length:{maximum:50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, length: { maximum: 255 }
                    #format: { with: VALID_EMAIL_REGEX }
                    #uniqueness: { case_sensitive: false }


  VALID_PHONE_REGEX=/\A[0-9]+\z/i
  validates :phone_no,length:{maximum:10}
  #format:{with:VALID_PHONE_REGEX}
  
  has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  #associations
  belongs_to :hostel , polymorphic:true
  

  belongs_to :student_result

  #validate :border_count_within_limit, :on => :create, :on => :update

  #def border_count_within_limit
   # if self.hostel.borders(:reload).length >= self.hostel.no_of_rooms
    #  errors.add(:base, "Exceeded thing limit")
    #end
  #end

end

app/models/choice.rb
class Choice < ApplicationRecord
	has_many :roommates ,:dependent => :destroy

	has_many :room_choices,:dependent => :destroy
end

app/models/himadri.rb
class Himadri < ApplicationRecord
	has_many :borders, as: :hostel
	 
end

app/models/himgiri.rb
class Himgiri < ApplicationRecord
	has_many :borders, as: :hostel
end

app/models/hostel.rb
class Hostel < ApplicationRecord
	validates :hostel_name ,presence: true,uniqueness:true
end

app/models/kailash.rb
class Kailash < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/ki.rb
class Ki < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/kiru.rb
class Kiru < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/manish.rb
class Manish < ParentHostel
 has_many :borders, as: :hostel
 end

app/models/neelkanth.rb
class Neelkanth < ApplicationRecord
	has_many :borders, as: :hostel
	
end

app/models/preftab1.rb
class Preftab1 < ApplicationRecord
end

app/models/preftab2.rb
class Preftab2 < ApplicationRecord
end

app/models/preftab3.rb
class Preftab3 < ApplicationRecord
end

app/models/preftab4.rb
class Preftab4 < ApplicationRecord
end

app/models/roommate.rb
class Roommate < ApplicationRecord
	belongs_to :choice
end

app/models/temphostel.rb
class Temphostel < ApplicationRecord
end

app/models/thi.rb
class Thi < ParentHostel
 has_many :borders, as: :hostel
 end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
	def show
		@hostels=[]
		Hostel.all.each do |hostel|
			@hostels.push(hostel.hostel_name)
		end
	end

	def newhostel
		require './db/migrate/new_hostel_migration.rb'
		hostel_name=params[:hostel]["name"]
		hostel_name=hostel_name.downcase
		model_name = hostel_name.singularize.capitalize
		hostel_name=hostel_name.pluralize
		begin
    	NewHostel.create_with(hostel_name)
    	rescue ActiveRecord::StatementInvalid		#if table is already exist
    		flash[:danger]="#{hostel_name} is already exits"
    		redirect_to(setting_path) and return
    	end
    	Hostel.create(hostel_name:model_name)
    	flash[:success]="Hostel crated succesfully"
    	redirect_to(setting_path)
	end



	def import
		selected_hostel=params[:selected_hostel]
		hostel_class=selected_hostel.constantize
		begin
	  	hostel_class.import(params[:file])
	  	rescue
	  		flash[:danger]="File cant be imported please check file data or formate "
	  		redirect_to(setting_path) and return
	  	end
	  	flash[:success]="file is imported successfully"
	  	redirect_to(setting_path)
	end

	def import_student_result
		begin
		StudentResult.import(params[:file])
		rescue
	  		flash[:danger]="Result cant be imported please check file data or formate "
	  		redirect_to(setting_path) and return
	  	end
	  	flash[:success]="Result is imported successfully"
	  	redirect_to(setting_path)
	end

	def create_profile
		roll_nos=StudentResult.all.map(&:roll_no)
		@password={}
		roll_nos.each do |roll_no|
			if Border.find_by(roll_no:roll_no).nil?
				result=StudentResult.find_by(roll_no:roll_no)
				#pass=((1..9).to_a+('a'..'z').to_a+('A'..'Z').to_a).shuffle[5,15].join
				pass="1234567"
				a=Border.create(roll_no:roll_no,student_result_id:result.id,password:pass,password_confirmation:pass,hostel_id:1,hostel_type:"Temphostel")
				@password[roll_no]=pass
			end
		end
	respond_to do |format|
        format.html
        format.xlsx
     end
		
		
	end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/create_profile.html.erb
<%=@r%>
<%=@b%>
<%=@c%>
<%= link_to 'Download as .xlsx', borderslist_path(format: :xlsx) ,class:"btn btn-primary btn-block" %>

app/views/settings/newhostel.html.erb
<%=@a%>

app/views/settings/show.html.erb
  <nav class="navbar navbar-default navbar-static-top nav-set " role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#indexnav">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
    <a class="navbar-brand" href="#">ADMIN INTERFACE</a>
    </div>
    <div class="collapse navbar-collapse navbar-right " id="indexnav">
      <ul class="nav navbar-nav nav-tabs">
         <li><%= link_to "PROFILE",adminprofile_path(current_admin.id)%></li>                           
         <li><%= link_to "LOGOUT",adminlogout_path ,method: "delete"%></li>  
        </ul>
    </div>
  </div>
  </div>
</nav> 
<div class="panel set-margin">

<div class="row set-body-margin jumbotron">
    <%= render 'shared/flash'%>
      <div class="col-md-6 col-md-offset-3 col-sm-6 col-md-offset-3 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading text-center ">
              <h2 class="panel-title">ADD NEW HOSTEL</h2>
          </div>
          <div class="panel-body text-center">
            <%= form_for(:hostel, url: newhostel_path) do |f| %>
              <div class="form-group">
                 <%= f.label :"Enter the new hostel name in singular form" %>
                <%= f.text_field :name, class: 'form-control',id:"examplehostel",placeholder:"enter new hostel name" %>
              </div>
              <div class="form-group">
              <button type="submit" class="btn btn-md btn-default">ADD HOSTEL</button>
            </div>
            <%end%>
            </div>
            <!-- uploading rooms for hostels -->
            <div class="panel-heading text-center ">
              <h2 class="panel-title">IMPORT ROOMS</h2>
          </div>
          <div class="panel-body text-center">
            <%= form_tag import_path, multipart: true do %>
              <div class="form-group">
                <select list="hostel_name" name="selected_hostel" class="form-control " required="required"  placeholder="-Hostel-" />
                  <option value="" disaled selected>Select Hostel</option>
                  <%= @hostels.each do |hostel| %>
                    <option value=<%=hostel%>><%=hostel%></option>
                   <% end %>  
                </select>
            </div>
            <div class="form-group">
              <%= file_field_tag :file,id:'fileupload' %>
              <%= submit_tag "IMPORT ROOMS", class:"btn btn-default " %>
            </div>
            <% end %>
            
          </div>
          <div class="panel-heading text-center ">
              <h2 class="panel-title">IMPORT RESULT</h2>
          </div>
          <div class="panel-body text-center">
            <%= form_tag import_student_result_path, multipart: true do %>
            <div class="form-group">
              <%= file_field_tag :file,id:'fileupload' %>
              <%= submit_tag "IMPORT RESULT", class:"btn btn-default " %>
            </div>
            <% end %>
            
          </div>
          <div class="panel-heading text-center ">
              <h2 class="panel-title">CREATE PROFILE</h2>
          </div>
          <div class="panel-body text-center">
            <%= link_to "CREATE PROFILE OF NEW STUDENTS", create_profile_path(format: :xlsx),method: :post,class:"btn btn-default"%>
            
          </div>
        </div>
        </div>
      </div>
</div>

app/views/settings/show1.html.erb
<h1>This is setting page for admins</h1>

<ul>

	<h2>Add New Hostel</h2>
	<%= form_for(:hostel, url: newhostel_path) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <span>Please enter the name of hostel in plural form i.e himgiris</span>


      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
</ul>

<ul>


<h2>Import rooms</h2>

<%= form_tag import_path, multipart: true do %>
<div class="form-group">

   <select list="hostel_name" name="selected_hostel" class="form-control " required="required"  placeholder="-Hostel-" />
     <option value="" disaled selected>Select Hostel</option>
         <%= @hostels.each do |hostel| %>
          <option value=<%=hostel%>><%=hostel%></option>
            <% end %>  
   </select>
</div>
  <%= file_field_tag :file %>
  <%= submit_tag "Import",name:import %>
<% end %>


</ul>